IgnorePacketTypeZero = true

AddHook("OnPacket", "OnPacket", function(pkt)
  if pkt.type ~= 0 and IgnorePacketTypeZero then
    print("OnPacket type:     " .. pkt.type)
    print("objtype:  " .. pkt.objtype)
    print('count1 :'..pkt.count1)
    print('count2 :'..pkt.count2)
    print("netid:    " .. pkt.netid)
    print("item:     " .. pkt.item)
    print("flags:    " .. pkt.flags)
    print("int_data: " .. pkt.int_data)
    print("pos_x:    " .. pkt.pos_x)
    print("pos_y:    " .. pkt.pos_y)
    print("pos2_x:   " .. pkt.pos2_x)
    print("pos2_y:   " .. pkt.pos2_y)
    print("int_x:    " .. pkt.int_x)
    print("int_y:    " .. pkt.int_y)
    print(" ================== ")
  end
end)

AddHook("OnRawPacket", "OnRawPacket", function(pkt)
  if pkt.type ~= 0 and IgnorePacketTypeZero then
    print("RAW type:     " .. pkt.type)
    print("objtype:  " .. pkt.objtype)
    print('count1 :'..pkt.count1)
    print('count2 :'..pkt.count2)
    print("netid:    " .. pkt.netid)
    print("item:     " .. pkt.item)
    print("flags:    " .. pkt.flags)
    print("int_data: " .. pkt.int_data)
    print("pos_x:    " .. pkt.pos_x)
    print("pos_y:    " .. pkt.pos_y)
    print("pos2_x:   " .. pkt.pos2_x)
    print("pos2_y:   " .. pkt.pos2_y)
    print("int_x:    " .. pkt.int_x)
    print("int_y:    " .. pkt.int_y)
    print(" ================== ")
  end
end)

AddHook("OnIncomingRawPacket", "OnIncomingRawPacket", function(pkt)
  if pkt.type ~= 0 and IgnorePacketTypeZero then
    print("OnIncomingRawPacket type:     " .. pkt.type)
    print("objtype:  " .. pkt.objtype)
    print('count1 :'..pkt.count1)
    print('count2 :'..pkt.count2)
    print("netid:    " .. pkt.netid)
    print("item:     " .. pkt.item)
    print("flags:    " .. pkt.flags)
    print("int_data: " .. pkt.int_data)
    print("pos_x:    " .. pkt.pos_x)
    print("pos_y:    " .. pkt.pos_y)
    print("pos2_x:   " .. pkt.pos2_x)
    print("pos2_y:   " .. pkt.pos2_y)
    print("int_x:    " .. pkt.int_x)
    print("int_y:    " .. pkt.int_y)
    print(" ================== ")
  end
end)

AddHook("OnIncomingPacket", "OnIncomingPacket", function(pkt)
  if pkt.type ~= 0 and IgnorePacketTypeZero then
    print("OnIncomingPacket type:     " .. pkt.type)
    print("objtype:  " .. pkt.objtype)
    print('count1 :'..pkt.count1)
    print('count2 :'..pkt.count2)
    print("netid:    " .. pkt.netid)
    print("item:     " .. pkt.item)
    print("flags:    " .. pkt.flags)
    print("int_data: " .. pkt.int_data)
    print("pos_x:    " .. pkt.pos_x)
    print("pos_y:    " .. pkt.pos_y)
    print("pos2_x:   " .. pkt.pos2_x)
    print("pos2_y:   " .. pkt.pos2_y)
    print("int_x:    " .. pkt.int_x)
    print("int_y:    " .. pkt.int_y)
    print(" ================== ")
  end
end)

AddHook("OnTrackPacket", "OnTrackPacket", function(pkt)
  if pkt.type ~= 0 and IgnorePacketTypeZero then
    print("OnTrackPacket type:     " .. pkt.type)
    print("objtype:  " .. pkt.objtype)
    print('count1 :'..pkt.count1)
    print('count2 :'..pkt.count2)
    print("netid:    " .. pkt.netid)
    print("item:     " .. pkt.item)
    print("flags:    " .. pkt.flags)
    print("int_data: " .. pkt.int_data)
    print("pos_x:    " .. pkt.pos_x)
    print("pos_y:    " .. pkt.pos_y)
    print("pos2_x:   " .. pkt.pos2_x)
    print("pos2_y:   " .. pkt.pos2_y)
    print("int_x:    " .. pkt.int_x)
    print("int_y:    " .. pkt.int_y)
    print(" ================== ")
  end
end)